### ISSUE TITLE
Break or clarify dependency between VM objects and platforms

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#112]
When a new Krun schedule is created, a `krun.config.Config` object is created, based on a configuration file on disk. The constructed `Config` object contains a number of VM definitions, based on the classes in `krun.vm_defs`. Each of these objects needs to know about the platform on which they are running, so each VM object has a `set_platform()` method which needs to be called after the VM has been constructed.

This creates an awkward dependency between all the objects that have to be created to run a schedule. Initially, the `krun.py` file dealt with this in `main()`, meaning that client code (including unit tests) had to explicitly manage object initialisation in the correct order. 

PR #111 moved this code into the constructor of `krun.scheduler.Scheduler`, so that anyone creating a full scheduler can forget about object initialisation. Other client code (including some unit tests) will still need to call `set_platform()` by hand. This is not particularly clean.

At the very least it these dependencies should be clearly documented.

**Comment by vext01** [comment]
@snim2 is there still interest in fixing this?

**Comment by vext01** [comment]
Let's kill this, as the code has changed a *lot* since then. OK @snim2
