### ISSUE TITLE
Rework run_shell_cmd()

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#119]
As discussed with @snim2:

* Move `util.run_shell_cmd()` into the platform instance.
   * It should accept an optional argument `user`, which if not `None` uses `sudo` or `doas` to invoke the command as another user
   * It should accept a list of arguments, and never a string.
* We should replace any manual `os.system()`, `subprocess.Popen()` with calls to the new method.

**Comment by ltratt** [comment]
We've done this (and much more) recently.
