### ISSUE TITLE
ETA doesn't account for startup sleeps in reboot mode

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#125]
ETAs in reboot mode are currently a little optimistic due to the fact that they don't account for the sleeps that allow the system to come up.

**Comment by ltratt** [comment]
If we're being clever, krun can notice that it's done N executions and count how long they all took. It can then subtract that amount from the time between "now" and "when we started the experiments", and then divide it by the number of process executions. This will give a good average of how long it took krun to reboot and start running a benchmark.

**Comment by vext01** [comment]
Assigned "camera ready" milestone. For the real experiment, we want to minimise the SSH activity to the machine during benchmarking.

**Comment by vext01** [comment]
Duplicate of #127
