### ISSUE TITLE
Make more parameters configurable (was "Startup sleep duration should be configurable.")

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#126]
```
# Wait this many seconds for the network to come up.                            
STARTUP_WAIT_SECONDS = 3 * 60
```

This should probably be configurable via config file.

**Comment by vext01** [comment]
There actually are many hard-coded parameters that could go into the config file with sensible defaults. Renamed issue to reflect this.

**Comment by ltratt** [comment]
I think that we will do these on an as-needed basis (i.e. if users squeal), but we don't need to do so proactively. Closing.
