### ISSUE TITLE
Handling of heap limits is broken since user switch logic was introduced.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#133]
Krun tries to limit the amount of heap space available to each VM. This is configured by config file. For the warmup experiment, we use 2GB.

When running the VMs, krun does the following:

 * First it uses the Python module `resource` to drop the krun processes heap limit.
 * Second, where possible, krun passes arguments to the VM executables reflecting the heap limit.

This worked for us before user switching was implemented, as Python's `Popen` would simply fork/exec thus inheriting the heap limit from the krun process.

When we implemented user switching however, we broke the heap limit. Because we use `sudo` or `doas` to become another user, a new shell is created and the heap limit is not inherited from the parent krun process.

I stumbled across this problem indirectly. It took me a fair while to figure out what was going on. On OpenBSD, the JVM was complaining that ti could not allocate it's heap, but only in `--develop` mode (we ask the JVM to limit its heap with the argument `-Xmx2097152K`). Weird, I thought. So this should also be failing on Linux... Nope.

Turns out, if you ask the JVM to use a 2GB heap:

 * On Linux, the process uses 2GB of RAM (surprise). The process runs under `--develop` just fine.
 * On OpenBSD, it uses close to 3.5GB, thus maxing out the ulimit. Hence the crash under `--develop`.

So the bug is not when `--develop` is switched on, it is when it is switched off, as the heap limit is not in place!

That explains the crash, but there is something more deep here. `-Xmx` makes the JDK pre-allocate the maximum heap size up-front, which is not what I expected, or what I want. It may cause artificially long startup times, for example.

Note also that some VMs don't provide arguments that allow us to limit the heap.

Having thought this over -- although I would like confirmation -- I think the right thing to do is to:

 * Never pass any VM specific arguments that attempt to limit the heap.
 * Limit the heap solely via ulimits on the krun user (e.g. on OpenBSD just set the heap limit in `login.conf`. I suppose linux has some similar knob somewhere).

I think this is more fair, and less error prone.

Thoughts @snim, @ltratt, @cfbolz ?

**Comment by ltratt** [comment]
I don't pretend to fully HotSpot's memory allocation stuff, but what I do understand suggests it's a mess. However, the pre-allocation *probably* isn't doing what you're thinking it is. IIRC, it's requesting space from the OS, but that doesn't mean it's using it. In other words, it's probably reserving part of virtual memory but not reading / writing to it. This is likely to be *extremely* cheap.

That said, given the particular benchmarks that we're running, I think HotSpot's defaults will be fine and we should simply live with them.

We should however be careful that each process on each machine has the same ulimit datasize and stacksize (both the "default" ulimit and "max" ulimit) to try and minimise one or other VM doing something silly on one machine.

**Comment by vext01** [comment]
I see.

Do you agree that we should limit the heap only using ulimits, never with additional VM-specific arguments?

**Comment by ltratt** [comment]
Yes.

**Comment by vext01** [comment]
OK, I think we can remove some code. PR coming.

**Comment by ltratt** [comment]
But notice: your bug report does say the ulimits that different users currently see varies according to machine / OS. We need to make sure that all processes have the same ulimit.

**Comment by vext01** [comment]
I'm not sure what you mean. The systemwide ulimit for the krun user is the one that will be used for all executions and VMs.

**Comment by ltratt** [comment]
How do we know that different machine / OS combinations are setting the same ulimit ceilings? One machine might say to a benchmark "you have 8GiB max to run in" while another might say "you have 2GiB max to run in". That may -- *may* -- cause the VM to behave slightly differently.

IMHO, we should ensure that the stacksize and datasize ulimits that processes see are the same on all machine / OS combinations.

**Comment by vext01** [comment]
You mean you want krun to write a heap limit into login.conf?

**Comment by ltratt** [comment]
No, that would be too difficult to get right, particularly across platforms.

One way of doing this is to have the `doas` / `sudo` call first invoke a script (which we control!) which sets the ulimit. There may be better ways of doing it though.

**Comment by vext01** [comment]
Right -- the ulimit would alrady have to be set >= our limit for this to work. It may be enough to execute out to `ulimit -d <blah> && <run the benchmark>`.

**Comment by vext01** [comment]
Similarly for the stack...

**Comment by ltratt** [comment]
Yes, that may work (it might need wrapping in `sh -c 'ulimit -d ... && benchmark'`, but I'm not sure).

**Comment by vext01** [comment]
You can just pass `shell=True` to Popen, but we lose automatic escaping of spaces in filenames etc. Since we don't have any of those we might get away with it.

**Comment by ltratt** [comment]
I'm not sure I trust that option. TBH, I'd probably be happier to write out an intermediate script to a temporary file and then execute that via `sudo`. That seems the way that's least likely to go wrong.

**Comment by vext01** [comment]
Well that wouldn't change the situation, as we would still lose the ability to automatically escape arguments. We would have to manually escape them as we write them to the script file, no?

**Comment by ltratt** [comment]
Yes, it doesn't change escaping. But we'd know exactly what shell we're executing (we can force `/bin/sh` or `/bin/ksh` or whatever we want, rather than relying on whatever the user happens to have specified in `/etc/passwd`).

**Comment by vext01** [comment]
Yes i see. That clearly trumphs.

**Comment by ltratt** [comment]
Of course, now we need to make sure we execute the same shell on different machines. IIRC, on Linux `/bin/sh` is often bash. It would be OK to use `bash` on all machines, or we could force `ksh` or whatever.

**Comment by vext01** [comment]
Hrm, that's a pain. Then we have to worry about the shell version etc. Thoughts?

**Comment by ltratt** [comment]
We can't worry about versions, or we'll go mad. But I think using the same shell is a good idea -- after all, not all shells respond to the `ulimit` command in the same way! I think it would be fine to say "they're all `bash` or `zsh` or whatever".

It looks like benchers 3 and 5 use `dash` for `/bin/sh`. Installing that on OpenBSD and using it wouldn't be too difficult.

**Comment by vext01** [comment]
It's in ports.

**Comment by ltratt** [comment]
Indeed ;)

**Comment by ltratt** [comment]
My suggestion would be that we search for `dash` in `bin`, `/usr/bin`, and `/usr/local/bin/` and complain if we can't find it.

**Comment by vext01** [comment]
I was just going to search the path with `find_executable`, since we don't mind which version of dash we find.

**Comment by ltratt** [comment]
Fine with me.

**Comment by vext01** [comment]
This was fixed by #134 and #135.
