### ISSUE TITLE
Improving the "benchmark started" email

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#141]
Since users will start a benchmark run and not want to ssh into the b/marking box again, it would be nice for the benchmark-started email to contain a few more details. This would make it easier to catch config mistakes after a run has started.

An easy fix for this issue would just be to email out the contents of the config file.

**Comment by vext01** [comment]
Works for me.

**Comment by snim2** [comment]
And the command line switches passed to Krun.

**Comment by vext01** [comment]
Since we now have the ability to copy a results file to a remote host via a post-exec hook, I wonder if we should just include the invocation into the results file. The config file is already in the results file.

**Comment by ltratt** [comment]
Sounds like a plan to me.
