### ISSUE TITLE
Test user user change command better.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#142]
Test user change command better. Probably a new test file for vm_defs.

**Comment by snim2** [comment]
I'm not quite sure I understand this feature request. Can we have a more detailed spec?

**Comment by vext01** [comment]
I was referring to the functionality where krun switches user to run benchmarks. Probably I observed that there is little in the way of testing.

**Comment by ltratt** [comment]
Unless anyone strongly objects, I think I should close this issue.

**Comment by vext01** [comment]
fwiw: the user change code has likely changed since this bug was raised.

**Comment by ltratt** [comment]
Does that mean we should/shouldn't close this?

**Comment by vext01** [comment]
I'd say close it.
