### ISSUE TITLE
Log less, log smarter

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#151]
Krun logs a *lot* of stuff. In production mode, we should be careful that we don't generate IO that may happen during benchmarking (since the OS may delay file writes etc.).

I think we should take the following philosophy: Krun should not perform any IO before or during a process execution. So we can safely write to the log when Krun is first started, since the machine will be rebooted shortly afterwards; and we can safely write to the log after an in-process execution has completed, again because rebooting will occur shortly afterwards.

**Comment by vext01** [comment]
I think it's OK to log prior to a process execution as long as we invoke a sync() right before benchmarking. The logging library already ensures that the log stream is flushed at the Python level (see #143 for my investigation into the logging module).

**Comment by ltratt** [comment]
I could write a long thing, but ultimately: no. We simply don't have any guarantees about `sync`s behaviour. Why risk it?
