### ISSUE TITLE
Deprecate --develop and --dryrun?

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#157]
It seems that whenever I am testing krun and reach for `--develop` or `--dryrun`, I find that I want to disable a different subset of production features than these options provide.

I wonder if we should instead split these options out into many individual flags, such as: `--x-fake-process-executions`, `--x-no-temperature-checks`, `-x-fake-reboots`, ...

**Comment by ltratt** [comment]
Shouldn't these just be options in the config file rather than impossible to remember CLI switches?

**Comment by vext01** [comment]
I don't mind where they live, but what makes config file options easier to remember?

**Comment by ltratt** [comment]
IMHO, the problem with commands that have lots of CLI switches is a) they start breeding like rats b) they interact like spaghetti c) documenting this becomes impossible. Of course, this isn't black and white, and there are many acceptable shades of grey.

**Comment by vext01** [comment]
I'm neutral about where the options live, just as long as we have fine-grained control over the various options that skip production-mode checks. Since you prefer config variables, we could roll with this.

I'm also going to downgrade the priority as I think I overestimated this.

**Comment by snim2** [comment]
Whether the options are in the config file or the CLI switches, there is still an overhead on the user to remember all the options. To my mind, the user will probably want to use the same config file in different ways, and we probably want to minimise the number of times the user has to edit the configuration, when they aren't changing their VM / language / benchmark options. 

The problem we have with the current CLI switches is not so much that there are too many of them, but in the case of `--develop` and `--dry-run` we named the switches in a very confusing way,

**Comment by vext01** [comment]
Having worked more on krun, and having watched @snim2 work on travis, I think that the debugging options we are proposing to add here are best as switches.

 * When developing krun, it's easier to tack on switches quickly, rather than open an editor, locate the right line...
 * If you forget the name of a switch,  `-h` will list them all.
 * You can't forget to document a switch, as the argument parser requires at-leas t a short description of each switch.
 * Tacking on command line switches to make krun on travis is much easier than having a separate config file for travis, or worse patching existing config files.

Regarding spaghetti interactions, I think this is a separate issue. The logic will be the same regardless of whether the options are a switch or a config file option. To avoid spaghetti, we have to try hard to keep the switches orthogonal. E.g., never `if not fake_reboots and no_sync:` like conditions.

Off the top of my head, these are the switches I would like implemented:
 * `--fake-reboots`
 * `--no-sync`
 * `--no-temp-wait`
 * `--no-pinning`
 * `--no-pstate-check`

Probably a few others, but the main ones I constantly fine myself commenting code out for are syncs and temperature code.

**Comment by ltratt** [comment]
5 switches, IMHO, is too many -- no-one but you will remember them, or be entirely clear what they mean. Why, for example, would someone want `no-sync`?

**Comment by vext01** [comment]
Because without it, you either have to wait 30 seconds for a sync to test the example, or you have to find the sync code and comment it out.

**Comment by ltratt** [comment]
I wonder if we have two categories of things:
  * Turning off features your platform might not have (pinning, pstate)
  * Making "dry runs" quicker (fake reboots, temp wait, no sync)
I can see that we need a flag for each of the first category, but the second category could just as easily be "quick dry run" or something?

**Comment by vext01** [comment]
@ltratt We currently have a --dryrun switch, but it's too coarse for many development situations. This is the main reason this issue has been raised.

**Comment by ltratt** [comment]
So can we bundle up all the "remove delay" stuff into one switch?

**Comment by vext01** [comment]
Yes, but I fear this will be too coarse too.

I don't understand your comment about remembering the switches. Only developers would need said switches, and they could find them with `--help`.

**Comment by vext01** [comment]
@snim2 what do you think?

**Comment by snim2** [comment]
I agree that we have a large number of switches, but I don't think that coarse-grained switches for these situations would help. For example, if I want to test pinning but I don't have a tickless kernel, I couldn't test krun with a `--no-custom-os` switch. If we want to clarify that these switches are not to be used for "real" benchmarking then we could just name them carefully, e.g.: `--fake-benchmark-no-tickless` or `krun-develop-no-tickless` or something -- it doesn't matter that the names are long as it should really only be us and Travis who use them.

**Comment by vext01** [comment]
Another example situation: I want to skip all delays apart from temperature waits, as I'm debugging the temperature sensor code on a new platform.

**Comment by ltratt** [comment]
I don't think that debugging new platforms is a good argument for a command-line switch. Each has a substantial cognitive overhead (and takes time to write, debug, document, update etc).

I can see a good argument for switches for platform-dependent features (tickless etc). I don't see a good argument for switches for each "stop something that introduces delays".

**Comment by vext01** [comment]
I disagree, but what you propose is better than the current situation.

Let's do that for now.

**Comment by snim2** [comment]
I would like to still be able to run Krun on both my laptop and Travis.

**Comment by ltratt** [comment]
@snim2 Why would what I propose stop you doing that?

**Comment by snim2** [comment]
It isn't clear to me whether it would or not. Turning off "platform-dependent" features might mean turning them off where they can't work, or having a switch to turn them off on any platform.

**Comment by ltratt** [comment]
There's no point Krun second-guessing the user, so the platform-dependent switches should always be available. If the user turns such a feature off, it doesn't matter whether there's actually something underneath to turn off or not: the end effect is the same.

**Comment by snim2** [comment]
OK, that sounds workable.

**Comment by vext01** [comment]
Alright, I would like to tackle this as two separate units of work:

 * Bundle delays into a `--quick` switch.
 * Implement platform specific switches, like `--no-pstate-check` and `--no-tickless-check` etc.

If that's OK with you guys, I will close this and raise two separate issues.

**Comment by snim2** [comment]
+1

**Comment by vext01** [comment]
Superseded by #203 and #204.

**Comment by ltratt** [comment]
Fine with me.
