### ISSUE TITLE
Kill daemons

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#160]
Laurie would like to try killing cron and smtpd prior to benchmarking.

**Comment by ltratt** [comment]
This may be the best ever title for an issue!

Yes, Laurie would. And he's also suggesting that there's part of the user config file which allows users to specify which things are killed (e.g. `["smtpd$", "cron$"]`). I suggest that the killing is done *after* krun has done its "wait for 3 minutes after rebooting" thing (which is enough time for e.g. smtpd to send status emails).

**Comment by vext01** [comment]
Sounds good.

**Comment by ltratt** [comment]
This is now implemented.
