### ISSUE TITLE
Reduce Krun's sleeping

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#170]
At the moment, I believe we wait 3 minutes after a reboot, then do a sync, then wait 30s. We could probably wait for 2.5 minutes, then run the "pre execution" commands (e.g. kill daemons), then do a sync and wait for 30 seconds.

[We should also check that the sync definitely happens *after* the "pre execution" commands are run.]

**Comment by vext01** [comment]
I can confirm that sync happens after the pre-execution hook. It's the last thing that happens prior to executing the benchmark: https://github.com/softdevteam/krun/blob/master/krun/vm_defs.py#L189

In light of that, I think all we need to do is lower the initial "wait for system to come up" wait. We could probably go lower than 2.5 mins(?). Optional extra, make the variable configurable. Thoughts?

**Comment by ltratt** [comment]
Sounds like a plan to me.

**Comment by vext01** [comment]
Fixed by #180
