### ISSUE TITLE
Make ETA available to pre/post execution commands.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#188]
It would be nice to set an variable which contains the ETA in the pre/post execution environment. This would allow us to monitor the ETA over time (it becomes more accurate over time)

Related: #125

**Comment by vext01** [comment]
I'm wondering why we decided this needs to be exposed to the pre/post-exec hooks. Would it suffice to simply store the ETA in the results file? (Under our scenario this is copied to bencher2 after each execution).

@ltratt, thoughts?

**Comment by ltratt** [comment]
My suggestion is two env variables, something like `ETA_GENERATED_AT` and `ETA_IS` (better names are probably not hard).

**Comment by vext01** [comment]
This is implemented.
