### ISSUE TITLE
Add some more developer docs

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#193]
There are a few internal conventions that are not fully documented, but might be useful to anyone wishing to work on Krun internals. E.g. that a "sanity check" is a dummy VM definition.

**Comment by snim2** [comment]
Add a clear description of what should go in a configuration file. Discussed briefly in #196

**Comment by ltratt** [comment]
Not that I disagree with this, but it's been hanging around so long that we've probably forgotten what it refers to... Closing.
