### ISSUE TITLE
Using `nice` results in an error on Linux

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#201]
The error is:

```bash
[2016-05-11 17:51:17: INFO] stderr: /usr/bin/nice: cannot set niceness: Permission denied
```

and can be seen on the (new) Travis builds.

**Comment by vext01** [comment]
How do I invoke krun to reproduce this?

**Comment by snim2** [comment]
Just use the example config with `--develop`. You can see the error on the new Travis builds.

**Comment by vext01** [comment]
Closing for now, as there was a lot of flux in the flags used in travis. I suspect this is fixed.
