### ISSUE TITLE
Move ENABLE_PINNING out of the config file and into a switch.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#207]
To quote a discussion from #206:

>My gut feeling is that pinning (and the like) should default to on, and throw an error if Krun can't make them work automatically. But there could then be a command-line to switch that need off. 

Pinning is already on by default, so we just need to move the option to a switch.

**Comment by ltratt** [comment]
Since we no longer pin, I'm not sure this issue is relevant anymore Edd? If so, can you close?

**Comment by vext01** [comment]
Yeah, close this.

Let's leave the pinning code in though.
