### ISSUE TITLE
Make dmesg filter rules configurable.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#213]
As it stands the rules are hard-coded in `platform.py`, the user should be able to configure these in the config file and on a per-platform basis.

**Comment by ltratt** [comment]
The plan here is to allow the user to specify a function `whitelist_dmesg_patterns` which takes a parameter `defaults` which is Krun's default whitelist. The function has to return a list of regular expression patterns: it's up to the user whether they then include the defaults or not.

**Comment by vext01** [comment]
Laurie, I think I have a cleaner solution which doesn't involve a callback. Let me show you this, then if you think it sucks then we can revert.

**Comment by ltratt** [comment]
OK.
