### ISSUE TITLE
dmesg whitelist

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#22]
Some OSs -- particularly Linux, it seems -- print continuous, voluminous, and not insightful output to their dmesgs. We need to add a blacklist feature so that known not-very-interesting things (e.g. segfaults) aren't reported to the user. I suggest that each platform has a default list of these things. For the time being, I think a crude mechanism is enough. Maybe in the future we might find that we want to allow users to add their own rules, but that's overkill for now.

**Comment by vext01** [comment]
I've actually not seen *any* junk come out of dmesg (on a non-broken machin) recently. I wonder if this is necessary.

**Comment by vext01** [comment]
Closing for now. Re-open if someone disagrees.
