### ISSUE TITLE
Instrument CPython

### ISSUE THREAD

**Issue by cfbolz** [softdevteam/krun#237]
Instrumenting CPython is hard, here's a link discussing how to measure GC pauses (answer: you can't :-( ): https://mail.python.org/pipermail/python-dev/2013-October/129552.html

**Comment by ltratt** [comment]
OK, another dumb question: if it can't be done, should we have an open issue for it? Or label it wontfix? Or ...?

**Comment by cfbolz** [comment]
can't be done easily ;-). We could patch the interpreter, for example.

**Comment by ltratt** [comment]
OK, I think there's very little chance of us doing this then. We could rename the issue "Instrument CPython" (at which point it sounds a bit more Krun-issue-like) and put it as low priority?

**Comment by cfbolz** [comment]
done

**Comment by vext01** [comment]
low priority sounds good to me.

**Comment by ltratt** [comment]
I'm going to close this issue: realistically, we're never going to have the bandwidth to do it.
