### ISSUE TITLE
Deal with APERF/MPERF in plotting

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#243]
We need a way to visualise the APERF/MPERF data in our plotting script.

Some background:

 * MPERF is a continually incrementing counter.
 * APERF is a counter incrementing only if the CPU is *on* (in C0 C-state)

From the Intel manual:

```
By default, the IA32_MPERF counter counts during forced idle periods as if the logical
processor was active. The 
IA32_APERF counter does not count during forced idle state. This counting convention allows
the OS to compute 
the average effective frequency of the Logical Processor between the last MWAIT exit and the
next MWAIT entry 
(OS visible C0) by ΔACNT/ΔMCNT * TSC Frequency.
```

Using the above equation we can compute the average effective frequency of the CPUs on a per-in-process-iteration basis.

I'm currently working on having Krun emit two more lists into the results file:

 * `aperf_data`: The sum of the differences between the APERF counters at the beginning and end of the iteration for all cores.
 * `mperf_data`: as above, but for MPERF.

Note that it would be possible to get a clock speed higher than the actual system clock speed, as we have summed N-cores worth of APERF/MPERF.

**Comment by snim2** [comment]
Thanks

**Comment by vext01** [comment]
Note that we don't yet know how to get the TSC frequency (probably an MSR or via CPUID), but I don't think we care, as it only scales the ratio, which we just want to know is flat over time.

**Comment by snim2** [comment]
Just a quick question about the data that will be in these keys, is there any chance that they might contain a NaN?

**Comment by vext01** [comment]
NaN cannot happen. The values come from `uint64_t`s in libkrun.

**Comment by snim2** [comment]
Should this be in warmup? (if so I will move it)

**Comment by vext01** [comment]
Bah, yes, sorry.
