### ISSUE TITLE
Status cookie

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#250]
At the moment, Krun starts off by taking in a results file, working out where it is in the sequence run, and then carrying on. The issue is that the results file grows over every reboot, so that Krun is consuming an unpredictable (well, growing) amount of memory before every process execution.

Instead, @vext01's suggestion is that we write a simple "status cookie" (a very small, fixed-ish size file) which Krun reads in. Krun then runs the benchmark, and only when the process execution is finished does it read in the results file and append to it.

**Comment by snim2** [comment]
This was fixed in #256
