### ISSUE TITLE
Fix "ETA for Current Session Available" email

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#280]
Krun should not send emails like this:

> Message from krun running on bencher2:
>
> ETA for current session now known: ????-??-?? ??:??:??

**Comment by snim2** [comment]
This was working on Oct 11, broken by Oct 17

**Comment by vext01** [comment]
Interesting. How do you know?

**Comment by snim2** [comment]
I looked back through all my emails from bencher2. This was working just before we merged the cookie branch and not long befer we made reboot-mode the default. Somewhere in there I think we stopped recording or reading the ETAs correctly.

**Comment by vext01** [comment]
it's likely to do with the introduction of the manifest file.
