### ISSUE TITLE
Something wrong with PyPy instrumentation.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#288]
![pypy](https://cloud.githubusercontent.com/assets/604955/20312349/0df11684-ab4b-11e6-9fe6-eeac03882839.png)

**Comment by vext01** [comment]
It could be the case that:

 * the GC data is in fact correct, but the PyPy GC is bust.
 * JIT times are being read from (absent) trace log events. They should be read from the `jit_times` key, not from the event tree.

**Comment by snim2** [comment]
Relevant code is here: https://github.com/softdevteam/warmup_experiment/blob/master/warmup/vm_instruments.py#L94-L134

**Comment by vext01** [comment]
Fixed
