### ISSUE TITLE
Rerun pexecs after APERF / MPERF violations

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#311]
Since Krun records APERF & MPERF data, it can also detect likely violations. Rather than recording the faulty data, it would be better to rerun the pexec.

Fortunately, I think we have most of the machinery necessary to make this easy. Immediately after a pexec has finished, we can check the APERF / MPERF data; if there are any violations, we simply don't record that the pexec completed. When we reboot, Krun will naturally rerun the pexec without us doing anything.

The only thing we will need to do is to work out how to express what the APERF / MPERF tolerances should be. We could automatically work them out (from `/proc/cpuinfo`'s speedstep things) or have the user manually specify them (or, I suppose, have an automatic value and allow the user to manually override it).

**Comment by vext01** [comment]
Thanks Laurie.

Additional notes/thoughts:

 * We would need to make the code that marks outliers a library routine so we could re-use it.
 * Decide a suitable threshold for "too many violations". Just one sample? 10? 20?
 * Send an email?
 * Bail after X attempts?

**Comment by ltratt** [comment]
I think the threshold must be if 1 or more in-process iterations triggers the fault.

Good point about the "bail after X attempts" thing though: I think we'd need that (although I think I'd set the default to be highish e.g. at least 10).

**Comment by vext01** [comment]
This has been fixed in #246

**Comment by ltratt** [comment]
Not that it's a big deal, but I don't think that #246 was the fix for this -- I think https://github.com/softdevteam/krun/pull/316 was.

**Comment by vext01** [comment]
You are right. My bad.
