### ISSUE TITLE
Consider using cron instead of rc.local

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#317]
As far as I can see, `README.md` doesn't tell users how to run Krun after a reboot. We should fix that before release.

Related to that is a thought I had that we might be able to do something nicer (and less easy to get wrong) than "edit `/etc/rc.local` (or equivalent)": we could use cron's `@reboot` mechanism. Then the users would just have to do something like "run `crontab -e`, add the line `@reboot /path/to/krun` to a blank line at the end of the file, then save".

I'm not suggesting we do this for 1.0, as it'll require careful testing, but it might make installation easier and less easy to get wrong. It means, for example, that one can no longer stop the machine from booting (which it's easy to do with a slightly careless line in `/etc/rc.local`).

**Comment by vext01** [comment]
@snim2 I think this can be closed now?

(I'm not so fussed about moving to using cron)

**Comment by ltratt** [comment]
There are two advantages of the `cron` approach.

1) I think everyone has `cron`, which means that we don't have to say "maybe you need to edit `/etc/rc.local` or something else depending on your machine"
2) If you mess up `/etc/rc.local` you end up locking yourself out of your machine (which we've done multiple times). You can't do the same thing with `cron`.

Now, one possible killer problem is that if `cron` runs `krun` and then `krun` kills `cron`, does that kill `krun`?

**Comment by vext01** [comment]
> maybe you need to edit /etc/rc.local

I guess, although most init systems to provide a backward compatible sysV style rc.local. The platforms we support both use `/etc/rc.local`.

There will be other portability issues that stop you in your tracks before rc.local does if we were to port to other Unixs and Linuxs though.

> If you mess up /etc/rc.local you end up locking yourself out of your machine

That's a stronger argument IMHO.

>  if cron runs krun and then krun kills cron, does that kill krun?

Possibly, not sure.

On a related note, there are a kajillion cron implementations in Linux land:
systemd, cronie, fcron, dcron, vixie-cron, scron, anacron

Don't ask me how compatible they all are (classic linux ;) )

I'm going to suggest we make this a low-priority issue.  It's not essential.

**Comment by ltratt** [comment]
Starting Krun as a daemon (https://github.com/softdevteam/krun/issues/317) should solve the "if cron starts krun and krun kills cron, does that kill krun" problem (and tongue twister).

**Comment by vext01** [comment]
Since #317 is now sorted, this can go ahead.

**Comment by vext01** [comment]
Fixed by #350
