### ISSUE TITLE
Krun must be started from tmux or screen (or maybe nohup).

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#336]
The reason I think we lost bencher6 this week...

I think I invoked Krun outside of a tmux (I usually invoke in tmux).

When run outside of a tmux, I speculate that, the SSH connection can drop once the network card is off, thus forcefully killing Krun. Because the kill is forceful, the post-exec commands can't run, thus the network card stays down.

Pure speculation. Seems plausible?

The fix is either:
  * Invoke in tmux
  * Invoke by reboot (once `rc.local` is in place -- should work, right?)

**Comment by ltratt** [comment]
Or have `krun` daemonise itself. Which is probably the best solution, in the sense that it's least effort for other users.

**Comment by vext01** [comment]
Indeed. This is effectively what tmux has done for us in the past, but I agree that doing it properly would be better.
