### ISSUE TITLE
Krun does not check if turbo mode is disabled on OpenBSD.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#340]
This is difficult because there is no access to MSRs in OpenBSD.

**Comment by ltratt** [comment]
This seems unresolvable to me. Maybe we can document it as a limitation, but it doesn't sound like we can fix anything?

**Comment by vext01** [comment]
At the time, I couldn't find any way of knowing if turbo mode was enabled on OpenBSD.

At the very least, there should be a line in `README.md`.
