### ISSUE TITLE
Dummy example is counterproductive

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#354]
The dummy example benchmark (which is effectively `sleep(1)`) consistently causes the CPU to throttle down to a ratio of about 0.5. The A/MPERF checker then rejects the result, thus we have an infinite loop.

Shall we kill the dummy benchmark in the example?

https://github.com/softdevteam/krun/blob/638b743125afb80a032fc00018b9f224d432536d/examples/benchmarks/dummy/python/bench.py#L43-L56

**Comment by ltratt** [comment]
We can just make it a loop that counts down from some large number?

**Comment by snim2** [comment]
We have dummy because we wanted an interpreted example which did not require people to run `make` over the Java stuff, so I think it's good to keep it and, as Laurie says, replace `sleep` with something else.

**Comment by vext01** [comment]
Laurie's idea works for me.

**Comment by vext01** [comment]
Hrm, I'm having cold feet about this.

I think a countdown loop will be optimised out by C and Java compilers.

How about we import one of the other warmup benchmarks instead?

fannkuch_redux is the next smallest benchmark to binarytrees --  I propose this.(binarytrees is already included as an example).

**Comment by ltratt** [comment]
Good idea.
