### ISSUE TITLE
Instrumentation mode doesn't show stderr in the event of a real crash.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#361]
CC @fsfod 

When a benchmark crashes, often useful crash information is output to stderr. Under normal circumstances, Krun will capture stderr and print it out in the event of a crash.

Under instrumentation mode, stderr is siphoned off to a file for later parsing and the error reporting is unaware of this, so in the case of a crash, it prints an empty stderr, which isn't helpful.

### Dumb fix

Get Krun to look into the file to print the error.

This is bad in the case of PyPy as it makes a ton of instrumentation output.

### Simple(?) Fix

Most instrumentation parsers use a regex to decided if a line is instrumentation data. In the case of a crash, print only the lines which didn't match.

Other ideas?

**Comment by fsfod** [comment]
can't you just add a new flag to vmdef class to say that instrumentation output is written to something else other than stderr

**Comment by vext01** [comment]
Yep, that's what I ended up doing. See #362
