### ISSUE TITLE
Add some means to set per benchmark environmental variables 

### ISSUE THREAD

**Issue by fsfod** [softdevteam/krun#366]
I need some way to set per benchmark environmental variables or at the minimum I need automatic  environmental variables that contains the benchmark name. To generate jitlog output file name in my iteration runner i would also need at least the VM name and pexec count.

**Comment by vext01** [comment]
Can you give me some context (without going too technical on the Lua side) as to why you need these?

Can you get the VM name and the benchmark name from argv?

**Comment by snim2** [comment]
^^^ For the sake of anyone reading this in the future, maybe we can fill in some of these details?
