### ISSUE TITLE
Help krun better track overlay .krun files

### ISSUE THREAD

**Issue by fsfod** [softdevteam/krun#368]
Currently krun overlay files are implemented by sticking `execfile("base.krun", globals())` at the top of the main krun file but krun has no idea about the extra .krun files loaded so they don't get embedded in the results json file. 
My idea was some official krun api to call instead of execfile to load the base .krun file so the base file also gets saved in the results file

**Comment by vext01** [comment]
No API would help here, since Krun simply loads the textual contents of the config file and throws it into the results file somewhere:

Here is it reading the config file in:
https://github.com/softdevteam/krun/blob/30d9c6b4d57b497dc3eb13e02ddc72c911223ce2/krun/config.py#L122-L123

Here is is copying it into the `Results` instance which eventually gets serialised:
https://github.com/softdevteam/krun/blob/30d9c6b4d57b497dc3eb13e02ddc72c911223ce2/krun/results.py#L85

There are a couple of things that spring to mind as potential fixes:
 * See if we can stringify the config file after it's interpretation, thus hopefully including all of whta gets included.
 * Store the config file as a JSON structure in the config file.

Any other thoughts?

**Comment by vext01** [comment]
@snim2 Maybe you have some ideas/comments on this one?

**Comment by snim2** [comment]
Ah, I think I missed the PR that changed all the example configs. To be honest, I'm not so sure how much clearer it is to share state in this way, it means the reader has to bounce around files quite a bit, but perhaps there is a use case there.

A neat long term solution might be to have an API where the base config was a class which could be subclassed. I suspect that would be tricky, but maybe we could just use `krun.config.Config` in that way?

**Comment by vext01** [comment]
A subclass would have the same issue.

Think about how the startup.krun config works. It goes like this:

startup.krun:
```
execfile("warmup.krun", globals())  # inherit the warmup config

ITERATIONS_ALL_VMS = 1
# more over-rides...
```

So this is the exact text copied into the config file audit in the results file. Tom's issue is that without also having `warmup.krun` in there, one cannot know the exact configuration.

**Comment by snim2** [comment]
Maybe I have lost my marbles, but instead of `execfile` we'd have an `import` statement, right?

**Comment by vext01** [comment]
But then the results file would just have an `import` in place of an `execfile`. The contents of the imported file would still not appear in the results file.

Here's a concrete example. This is the json in the 0.8 results result file for bencher5:
```
...
 "config": "execfile(\"warmup.krun\", globals()) # import the warmup definitions completely\n\n\n# this file is a minimally hacky way
```

Do you follow?

**Comment by ltratt** [comment]
Dumb question: why are we storing the config at all?

**Comment by vext01** [comment]
So that we can see under what conditions the experiments were run. Nothing more.

[There is a check that the config hasn't changed too, but I could live without that. As you said before, if the user does silly things, they get silly outcomes. We can't hold their hand all the time :)]

**Comment by vext01** [comment]
If we are feeling really foul, we can run `m4` over the config file first, and includes can be `m4` includes. Yeugh.

**Comment by ltratt** [comment]
I must admit that I don't think we can do the right thing here in the case that Tom's pointed out. *Maybe* we could track imports, but I'm not sure if that'll work.

So maybe the right answer is to remove this feature entirely?

**Comment by vext01** [comment]
Can you comment on my two above suggestions in the bullet list?

**Comment by ltratt** [comment]
They seem incidental given the big questions are surely: *can* we do this at all? *should* we do this at all? We would, at a minimum, have to track imports. That's sounding difficult and fragile to me already.

**Comment by vext01** [comment]
The latter is certainly possible. You'd serialise the `Config` instance to JSON.

The former is more convenient, since it would give an exact copy of the textual config file.

**Comment by ltratt** [comment]
Serialising arbitrary stuff is not as easy or reliable as it sounds. If the user does something a bit odd in their config file, everything will break in weird ways.

The more I think about it, the more I think we're trying to twist our knickers to an insane degree just to stop the user doing something that they aren't that likely to do anyway. My tentative vote is to simply delete the feature.

**Comment by vext01** [comment]
Give me a few minutes. If I don't find anything satisfying, we can kill this.

That doesn't help Tom mind :P

**Comment by ltratt** [comment]
I'm not sure if Tom's complaint is that Krun complains when he hasn't done something wrong or whether Krun doesn't complain when he has done something wrong. @fsfod which describes your use-case?

**Comment by vext01** [comment]
As far as I can see, he's trying to scrape the iteration counts out of the config stored in the results file. I'd advise against this anyway!

**Comment by vext01** [comment]
OK, this isn't easy.

I'm starting to come around to Laurie's way of thinking. I'm forever complaining that there's too much gubbins in krun, and here's an example. Let's burn some stuff.

This is my proposed plan of action:
 * Remove the `config` key from the results file.
 * Kill all the code that checks the config file didn't change.
 * When we archive data, also archive the config file(s) manually.
 * Tom looks at the data itself to see how many iterations there are.

**Comment by ltratt** [comment]
Just to be clear: there is another way that Tom can get the data/count he needs?

**Comment by vext01** [comment]
If I understand correctly, he's after the number of iterations.

In our other scripts we just ask the length of the time series.

If that's too annoying, we can add an extra keys, but there's probably no need:
```
{
    ...
    "in_proc_iters" : {
        "vm1": 2000,
        "vm2": 500,
    }
...
}
```

**Comment by ltratt** [comment]
@fsfod Is what Edd's said there correct?

[If so, it looks like Krun is just about to become simpler ;)]

**Comment by fsfod** [comment]
i was more talking generally about going back and checking what something was set to in the krun file for a particular result file

**Comment by vext01** [comment]
OK, so that's what this feature was designed for, but clearly without regard for `execfile` and friends.

Not sure where this leaves us.

**Comment by ltratt** [comment]
I think it was a reasonable feature, but we've now shown that it doesn't work, that even a partial fix isn't easy, and a guaranteed full fix probably impossible. Let's kill it. We'll all work out how to live without it.

**Comment by fsfod** [comment]
Couldn't we just make an artefacts zip or something instead if embedding is such a hassle

**Comment by vext01** [comment]
How would you know what to include without parsing the config file?

**Comment by fsfod** [comment]
I guess maybe an explicit api to register stuff

**Comment by vext01** [comment]
I suppose that could work, but is it really worth our time to implement it? I've got bigger fish to fry at the moment :(

**Comment by ltratt** [comment]
The problem with an explicit API is that the user has to get everything right every time or things break subtly. What we'd really need is a fully automated solution, but that's too difficult (probably impossible).

I think all we're really saying is that we need to say that it's the user's job to match config file(s) with result files. We can't really help them reliably with doing that.

**Comment by snim2** [comment]
Can I suggest, that where we currently store the whole config file, we just store the full path to that file (maybe with a hostname?) and it's modified timestamp. That way, the user has a chance of figuring out what the config might have been, but we aren't storing anything complicated.

**Comment by vext01** [comment]
It could work, yeah. @ltratt thoughts?

**Comment by ltratt** [comment]
Works for me.

**Comment by vext01** [comment]
OK, i'll be tackling this shortly. Maybe today.

**Comment by fsfod** [comment]
That wouldn't be much use to me the file will have changed since then

**Comment by snim2** [comment]
Is the file in version control?

**Comment by fsfod** [comment]
I hand edited to disable some benchmarks for some runs

**Comment by vext01** [comment]
If you *really* still want this feature, we could try serialising the following fields manually from the `Config` instance:
https://github.com/softdevteam/krun/blob/30d9c6b4d57b497dc3eb13e02ddc72c911223ce2/krun/config.py#L54-L71

You'd need to convince Laurie though.

**Comment by vext01** [comment]
Most of this is trivial, but `self.VMS` would need special care, as this contains an instance with its own nested configuration.

**Comment by fsfod** [comment]
I guess that would be a better way to do it

**Comment by vext01** [comment]
@ltratt ^^^ Thoughts?

Time estimate, half a day + review.

**Comment by ltratt** [comment]
Can we just cheat and serialise the keys from the VMs dict?

**Comment by vext01** [comment]
Yes, but that wouldn't tell you how the VM def was configured, e.g. was it in instrumentation mode, what extra environment was set...

**Comment by ltratt** [comment]
I'm not sure this is worth writing a custom serialiser for. If there's a quick fix that covers 80% of cases, fine, but a day and a half your time is probably not well spent IMHO.

**Comment by vext01** [comment]
Just to be clear, that's:
> half a day + review.

not "1.5 days".

**Comment by ltratt** [comment]
Hmm, maybe. I can still think of better ways to spend the time, if I'm honest. Do we have any evidence that anyone's ever shot themselves in the foot with this?

**Comment by vext01** [comment]
For me it's more about being able to do config archaeology years down the line when we have forgotten how all this works. If the user forgot to include their config file, you can't go digging. Here we force them to file their paperwork.

**Comment by ltratt** [comment]
Was this ever implemented? Will we ever implement it?

**Comment by snim2** [comment]
I think we did not, and @fsfod used a kludge of some sort.

**Comment by ltratt** [comment]
OK, I'm going to close; if anyone objects, they can reopen.
