### ISSUE TITLE
`virt-what` in Debian repos is too old to detect VMM hypervisors.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#369]
Whilst debugging a weird crash in Krun, I kicked up Debian 9 under VMM on my laptop. It was whining about there being no sensors, then about the scaler. I could have swore these were items which should not be checked in a virtual machine.

The issue is, `virt-what` from the debian repo is too old to detect vmm.

Old virt-what:
```
edd@debian:~/virt-what$ sudo virt-what
edd@debian:~/virt-what$
```

New virt-what:
```
edd@debian:~/virt-what$ sudo env PATH=`pwd`:${PATH} ./virt-what
vmm
```

We have two options:
 * Say that Krun requires a newer `virt-what`, (possibly fetching/building it at build time?).
 * Hack around it somehow (although neither `/proc/cpuinfo` nor `dmesg` mention VMM).

Annoying :\

**Comment by vext01** [comment]
Anyone have any thoughts on this one? It's making it pretty annoying to test under vmm vms.

**Comment by snim2** [comment]
I have a vague recollection that `virt-what` was one of several options we discussed when we started using it, so maybe there's another tool that does the same thing?

**Comment by vext01** [comment]
So `facter` seems to work:
```
edd@debian:~/research/krun/examples$ facter is_virtual
true
```

It's a ruby script, but is in the package repo. Also doesn't seem to need root, which `virt-what` does.

It's slower than `virt-what`, but I guess that hardly matters.

Thoughts?

**Comment by snim2** [comment]
Sounds sensible, does it work in BSD? I know `dmidecode` has a port...

**Comment by vext01** [comment]
dmidecode is in the openbsd packages yes, but it needs both root and kmem access. (kmem is pretty foul, but maybe OK for our setup).

https://man.openbsd.org/kmem

**Comment by vext01** [comment]
It would be an advantage to allow openbsd to know if it's virtualised. As it stands, `is_virtual()` always returns `false` in Krun/OpenBSD.

**Comment by snim2** [comment]
Well, you are in a better position than I am to know which of the options is best, but it seems like there's a way forward here somewhere.

**Comment by vext01** [comment]
Oops, `dmidecode` doesn't work on virtualised hosts:
```
edd@debian:~/research/krun/examples$ sudo dmidecode 
# dmidecode 3.0
Scanning /dev/mem for entry point.
# No SMBIOS nor DMI entry point found, sorry.
```

https://access.redhat.com/solutions/222903

**Comment by vext01** [comment]
Another option is to add a `--virtual` switch which the user can specify manually.

**Comment by vext01** [comment]
Any thoughts on that? @ltratt may object to a new switch.

**Comment by ltratt** [comment]
You know me too well ;)

If the only problem is that it doesn't currently work on vmm, then I think we should just accept that virt-what will eventually be upgraded on stable Debian. The last thing Krun needs is more flags ;)

**Comment by ltratt** [comment]
I think we should close this: it doesn't look like there's a fix that we'd want to do to Krun?

**Comment by ltratt** [comment]
Closing.
