### ISSUE TITLE
Warn if a/mperf is not configured

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#374]
Warn the user if they didn't set up a/mperf ratio tolerances.

**Comment by ltratt** [comment]
IIRC, we check the "did this processor clock down" bit and rerun based on that? If so, do we even need the tolerances any more?

**Comment by ltratt** [comment]
@vext01 Ping.

**Comment by vext01** [comment]
From `c7210108`:
> Changes in throttle flags now cause a re-run.

Reading the diff, the throttle counts are checked on Linux unconditionally.

They are read from a sysfs node.

So we could in fact close this, possibly removing a/mperf from Krun and the custom kernel at some point?

**Comment by ltratt** [comment]
> So we could in fact close this, possibly removing a/mperf from Krun and the custom kernel at some point?

I think so too.
