### ISSUE TITLE
Run benchmarks as a new user

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#53]
Run benchmarks as a new user, i.e. '_krun'. Make sure the user has a clean home dir and shell environment.

**Comment by snim2** [comment]
New user should have a known (and constant) environment size

**Comment by vext01** [comment]
Sarah have you started work on this?

**Comment by vext01** [comment]
I mat have trodden on your toes...

**Comment by snim2** [comment]
not yet...

**Comment by vext01** [comment]
phew. I was confused by "ready to publish" above. Mind if I assign myself?

In the future I need to check if someone is already assigned.

**Comment by snim2** [comment]
Sure
