### ISSUE TITLE
Reboot after each execution.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#54]
Reboot the system after every execution. Will require a systemd hook.

**Comment by snim2** [comment]
If I had a fix for this issue, how would I test it?

**Comment by vext01** [comment]
The top-level makefile in the warmup experiment has a `bench` target which kicks benchmarks off.

You might want to look at the config (`warmup.krun`) file to see what work this would do.

You will also probably need to adjust the json dumping code, as in it's current state it will overwrite the results.

**Comment by snim2** [comment]
I think my previous comment was not very clear! Are you testing krun by running it on your own machine? I'm just a bit concerned about testing this something like this and ending up in a reboot-loop. 

If I use the example config in `examples/` is that up to date with the rest of the source?

**Comment by ltratt** [comment]
I would test it on a bencher machine (best ask Edd which is free, and to give you an account if you don't have one).

**Comment by vext01** [comment]
I usually use a bencher.

The `examples` drectory is unlikely to work. I should just remove it. Instead, I recommend you use a subset of the warmup experiment. Clone the experiment and edit the config file to make a smaller experiment (e.g. use only a few vms [fast ones], only a few benchmarks, and a low execution and iteration count).

Hope that helps.

**Comment by ltratt** [comment]
An obvious question: how does rebooting interact with temperature control? Should we record a temperature on first run, put that in a temporary file, and make sure that after each reboot the machine has gone back to that temperature? [I think that's the right approach, but I'm not sure.]

**Comment by ltratt** [comment]
I also think we want to make sure that Krun can operate in both reboot and non-reboot modes. Rebooting will slow things down considerably and, to say the least, is not multi-user friendly. When quickly checking things, one probably doesn't want to use the reboot mode.

**Comment by vext01** [comment]
@ltratt WRT temperature, yes record in temp file. Booting may heat up the machine. WRT reboot mode: I certainly want a non-reboot mode for testing and rough results.

**Comment by snim2** [comment]
What I propose for this is to change the `krun` software as little as possible, but introduce a new daemon which would sit in the background and deal with reboot-mode. So, a full run of a VM-benchmark set in reboot-mode would work like this:

  * Check the daemon is running, if not start it
  * Load an ordered list of the VM-benchmark pairs that need to be executed
  * Create an JSON file for results (which at this point will just contain audit info, etc.)
  * Run `N` iterations of the first VM-benchmark pair
  * Append the VM-benchmark results to the JSON file
  * Save a line in a file in `/var/log/krun.log` which states which VM-benchmark pair was last run
  * Instruct the daemon to reboot
  * After reboot the daemon starts `krun` again (as the `krun` user)
  * `krun` finds the file in `/var/log` and works out which VM-benchmark to run next
  * ... etc. until the list is exhausted

I think for Linux this should be quite straight forward, how different is BSD?

**Comment by ltratt** [comment]
I have to say, a daemon sounds like an awful lot more work than just starting krun from `rc.local`.

**Comment by vext01** [comment]
I'm not sure linux works like that ;)

**Comment by vext01** [comment]
Although if it had an equivalent, I do think it would be simpler.

**Comment by ltratt** [comment]
bencher3 has `rc.local`.

**Comment by vext01** [comment]
I stand corrected.

Sarah, Can I suggest that this depends upon #41, then we add the ability to reboot and pick up?

**Comment by vext01** [comment]
If we use rc.local, we should drop privileges pretty sharpish?

**Comment by vext01** [comment]
or even start krun already dropped priv.

**Comment by snim2** [comment]
This sounds sensible to me. So, if we build on #41 `krun` needs to call `/sbin/reboot` itself, right?

**Comment by vext01** [comment]
I guess that's the most obvious approach. You could use sudo to do this.

**Comment by ltratt** [comment]
In `rc.local` one could do something like `sudo -u krun <path to krun>' or similar. In other words, I don't think we need to modify krun.

And yes, krun should use sudo to do the reboot IMHO.
