### ISSUE TITLE
DOCUMENT KRUN!

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#57]
Krun is becoming complicated. We should document it.

**Comment by snim2** [comment]
This needs a couple of small changes to close:
  * Check `examples/` works on BSD and make any necessary changes
  * Add documentation for BSD to `examples/README.md`
  * Move the information in `examples/README.md` to the main README

**Comment by snim2** [comment]
Also:
  * Python must be python2.7 (see PR #74 )

**Comment by snim2** [comment]
Document the `mk_graphs.py` script. Requires:

  * matplotlib
  * statsmodels

**Comment by snim2** [comment]
For Linux, prefer `adduser` to `useradd`

**Comment by vext01** [comment]
Are we happy with the level of documentation at present? Shall we close this?

**Comment by snim2** [comment]
The original plan was to move this out of `krun/examples/README.md` and into `krun/README.md` once we have included some BSD notes. You can move it over now if you wish and put the other work in with Issue #87 ?

**Comment by vext01** [comment]
Sounds sensible.
