### ISSUE TITLE
Remove `warmup_upon_iter` and `N_GRAPHS_PER_EXEC` support.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#58]
Dealing with warmup and drawing graphs are not the responsibilities of krun

**Comment by snim2** [comment]
Can this be closed? GH search doesn't come up with any results for those terms in this repo

**Comment by vext01** [comment]
There may be some references elsewhere, but we can fix them as we find em.

**Comment by snim2** [comment]
Thanks. I can't find anything with egrep either, so I think we are safe.
