### ISSUE TITLE
Try to control floating point non-determinism

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#59]
https://randomascii.wordpress.com/2013/07/16/floating-point-determinism/

**Comment by ltratt** [comment]
Fortunately, I don't think we need to worry about this particular source. If a user program does something odd with floating point, our existing non-determinism checks will (or should) catch it. If a VM does something odd with floating point, then that's something that we're interested in measuring. So I think this should be "wontfix".

**Comment by vext01** [comment]
Yes and no. There are some compiler flags that we can set to attempt to proactively avoid determinism that may (e.g.) screw up checksums.

I'm going to leave the bug open for now, but we may end up closing it WONTFIX.

**Comment by vext01** [comment]
(C compiler flags)

**Comment by ltratt** [comment]
I imagine the flags interfere with optimisations, so it's a tricky call. Let's leave it until/unless we find it to be an issue.

**Comment by vext01** [comment]
I think this has reached a natural conclusion. Closing.
