### ISSUE TITLE
Tickless operation on linux

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#60]
As raised by ltratt, we may need to use tickless mode on linux:
http://lwn.net/Articles/549580/

Our debian 8 systems currently run idle tickless mode:
```
vext01@bencher3:~$ cat /boot/config-`uname -r` | grep HZ
CONFIG_NO_HZ_COMMON=y
# CONFIG_HZ_PERIODIC is not set
CONFIG_NO_HZ_IDLE=y
# CONFIG_NO_HZ_FULL is not set <--------------------- this would need to be on!
# CONFIG_NO_HZ is not set
CONFIG_RCU_FAST_NO_HZ=y
# CONFIG_HZ_100 is not set
CONFIG_HZ_250=y
# CONFIG_HZ_300 is not set
# CONFIG_HZ_1000 is not set
CONFIG_HZ=250
CONFIG_MACHZ_WDT=m
```

To fix this, we would need to build a custom kernel. Another impractical step unfortunately.

Opening bug for discussion. @ltratt @snim2 @cfbolz

**Comment by ltratt** [comment]
Impractical?

**Comment by snim2** [comment]
A lot of these kernel tuning issues we have found are Linux only, if we make these changes in a custom kernel then presumably we need to figure out whether any other OSs we use have similar tuning parameters?

**Comment by vext01** [comment]
Impractical in the sense that, it's yet another thing thrown in the mix to complicate benchmark setup. Maybe impractical is the wrong word.

@snim, yes. Although I don't expect to find controls for all of these things in every OS. As usual, it will be a "best effort" kind of affair.

**Comment by ltratt** [comment]
There is, I'm fairly sure, no equivalent in OpenBSD for example.

**Comment by vext01** [comment]
For a start, I'm going to just add a check that the kernel was compiled with full tickless support.

Automating this would be part of  #56.
