### ISSUE TITLE
Fixed version of mx

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#63]
Currently we download a random version of `mx` (whatever is the latest in the repository). We should instead used a fixed version (i.e. use a specific checkout).

[I'd prefer we don't fix the version yet, as I'm hoping to fix `mx` for OpenBSD.]

**Comment by vext01** [comment]
Yep, there's a load of stuff that needs to have it's version fixed.

This is really a warmup experiment issue.

**Comment by ltratt** [comment]
Agreed, this should be on the warmup repo. Apologies.
