### ISSUE TITLE
Provide a way to re-run a subset of experiments

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#73]
This issue came from the discussion on Issue #41 (from @vext01 )

Currently it is only possible to re-run a subset of a whole benchmark by deleting entries from the json bz2 file. This is quite fiddly as you have to uncompress and then locate the right lines to remove in a results file potentially with tens of thousands of lines, so I wonder if we could write a tiny tool to remove results by key.

**Comment by snim2** [comment]
Thinking about this again, I'm not sure how sensible this is. I can see that for some testing that users might want to do, resume mode may not be enough. On the other hand, we don't want to provide an easy way to do something that would produce invalid results. 

Thoughts? @vext01

**Comment by vext01** [comment]
I've been over the same thought process in my head a few times in the past. I'm not sure what the right answer is.

All I can say is that merging newer results into an existing json file using a REPL is frustrating and probably also error prone.

**Comment by ltratt** [comment]
I don't think this is something we need now, but it probably is useful for testing. I'd be happy for it to come with a big warning though, so that people don't mix and match data for publication!

**Comment by vext01** [comment]
works for me.

**Comment by snim2** [comment]
Must be recorded in audit...

**Comment by vext01** [comment]
I think this is implemented.
