### ISSUE TITLE
Minor refactorings of commonly used dictionaries

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#75]
This is from the discussion on PR #74 

Data from krun configuration files (and results files) is loaded when `krun.py` starts, and are used in various parts of the code. Usually parts of the configuration (such as filenames) are passed around as separate variables. It would be neater to factor these out into classes, so that a single object can be passed around (and tested).

**Comment by snim2** [comment]
Under this scheme, the `krun.util.audits_same_platform` should become a method.

**Comment by snim2** [comment]
In which case, this might be useful for the same-platform check:

http://stackoverflow.com/questions/328936/getting-a-unique-id-from-a-unix-like-system

**Comment by ltratt** [comment]
I still think `hostname` is an adequate proxy. There isn't a single method which is guaranteed to work, so let's stick with the simplest possible scheme. If it goes wrong, at least people will be able to understand why.
