### ISSUE TITLE
mk_graphs.py appears to be broken

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#76]
I think `mk_graphs.py` has fallen behind the changes in the rest of the repo. Running `mk_graphs.py` on a cut-down version of the examples config I get this:

```bash
$ ./mk_graphs.py examples/quick.krun 
Traceback (most recent call last):
  File "./mk_graphs.py", line 296, in <module>
    data_dct = json.load(fh)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Config file needed to reproduce:

```bash
import os
from krun.vm_defs import (PythonVMDef, JavaVMDef)
from krun import EntryPoint

# Who to mail
MAIL_TO = []

# Maximum number of error emails to send per-run
#MAX_MAILS = 2

DIR = os.getcwd()
JKRUNTIME_DIR = os.path.join(DIR, "krun", "libkruntime", "")

HEAP_LIMIT = 2097152  # K == 2Gb

# Variant name -> EntryPoint
VARIANTS = {
    "default-java": EntryPoint("KrunEntry", subdir="java"),
    "default-python": EntryPoint("bench.py", subdir="python"),
}

ITERATIONS_ALL_VMS = 1  # Small number for testing.

VMS = {
    'Java': {
        'vm_def': JavaVMDef('/usr/bin/java'),
        'variants': ['default-java'],
        'n_iterations': ITERATIONS_ALL_VMS,
    },
    'CPython': {
        'vm_def': PythonVMDef('/usr/bin/python2'),
        'variants': ['default-python'],
        'n_iterations': ITERATIONS_ALL_VMS,
    }
}


BENCHMARKS = {
    'dummy': 1000,
    'nbody': 1000,
}

# list of "bench:vm:variant"
SKIP=[
    #"*:CPython:*",
    #"*:Java:*",
]

N_EXECUTIONS = 1  # Number of fresh processes.
```

Benchmarks as in the `examples/` directory.

Related to Issue #48

**Comment by vext01** [comment]
I've not used this for a long time, and arguably it is not the responsibility of krun to draw graphs.

Do you (or would you if it worked) use this? If so, maybe it should be moved elsewhere, though I don't know where.

**Comment by snim2** [comment]
It's a nice thing to have, otherwise the results of a krun experiment are currently inscrutable. The question I have is how do we expect krun to be installed and how do we expect the results files to be consumed? Do we want krun installed system-wide, in which case `mk_graphs` needs to be called `krun_chart_results` or something and placed in `/usr/local/bin`. Or do we just expect the repo to be cloned into `/home/krun` and run from there?

**Comment by ltratt** [comment]
I think the most likely (and easiest!) scenario is krun being run from its repo.

**Comment by vext01** [comment]
Maybe one day krun will get packaged up properly, but for now I think we should leave it as a "clone and run" type of affair.

**Comment by snim2** [comment]
Having thought about this a bit more, I still think it's useful to show the user how to consume results files. So, I would propose that we fix mk_graphs and move it into `examples/`, so that it isn't a core part of krun.

**Comment by vext01** [comment]
I'm happy with that.

**Comment by snim2** [comment]
OK, I have done most of this. The mk_graphs is fixed and relies only on the results file. I've moved it into `examples/`. As soon as the other PRs are merged I can rebase and push.

**Comment by vext01** [comment]
ok, great, just looking at last few bits in the other PR
