### ISSUE TITLE
Proper CPU pinning.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#77]
At current, `isolcpus` on Linux only blocks user processes from a CPU and not kernel threads.

There is a tool called `cset` which *might* allow us to do proper CPU isolation, kernel threads and all. For a while it has been broken on Linux. I reported a bug to debian a while ago and they have finally responded saying it should be fixed:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796893

**Comment by ltratt** [comment]
"We believe that the bug you reported is fixed in the latest version of cpuset, which is due to be installed in the Debian FTP archive." I wonder when? If it's put in during the next few days, we could make use of it. Otherwise, perhaps it's for run number 2...

**Comment by vext01** [comment]
Going to suggest this as post-submission.

**Comment by ltratt** [comment]
It's still surely better to do *some* pinning? At least excluding other user tasks is almost certainly better than not doing so at all.

**Comment by vext01** [comment]
> At current, isolcpus on Linux only blocks user processes from a CPU and not kernel threads.

We currently use `isolcpus`, so we do have some pinning at least.

**Comment by vext01** [comment]
This is now irrelevant, as we found that pinning introduces artificial CPU contention between threads.
