### ISSUE TITLE
Port to OpenBSD

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#87]
`[2015-11-02 16:42:17: ERROR] I don't have support for your platform`

**Comment by snim2** [comment]
Related: #57

**Comment by vext01** [comment]
OpenBSD support was recently "scaffolded", but is far from complete. At least now it runs, but it does not system checks etc.

**Comment by snim2** [comment]
Reminder: documentation needs to be added to `README.md`

**Comment by vext01** [comment]
Is anything outstanding on this other than documentation? I think it is pretty complete by now.

**Comment by snim2** [comment]
I think you are right...

**Comment by ltratt** [comment]
Agreed, we can close this now.
