### ISSUE TITLE
Ruby runner uses wrong timer if run under JRuby.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#95]
This was originally report by @cfbolz here (https://github.com/softdevteam/warmup_experiment/issues/55):

The Ruby runner contains this code:

```
if /linux/ =~ RUBY_PLATFORM
    MONOTONIC_CLOCK = Process::CLOCK_MONOTONIC_RAW
else
    MONOTONIC_CLOCK = Process::CLOCK_MONOTONIC
end
```

however, on JRuby ``RUBY_PLATFORM`` is "java", thus the wrong timer is used. Here is a discussion how to fix this: https://www.ruby-forum.com/topic/150942

**Comment by vext01** [comment]
Another alternative is to try and call `clock_gettime_monotonic()` in libkruntime, but I don't know how hard calling C is in (J)ruby.

**Comment by cfbolz** [comment]
We may have to go for that, because it seems that jruby does not define ``Process::CLOCK_MONOTONIC_RAW``

**Comment by cfbolz** [comment]
Ok, chatted with Chris. There is no FFI in truffleruby yet. Thus we have to change truffleruby. I'll need some help with this, my java is not good enough. I think this is the beginning of the patch we need:

```
diff --git a/truffle/src/main/java/org/jruby/truffle/nodes/core/TrufflePrimitiveNodes.java b/truffle/src/main/java/org/jruby/truffle/nodes/core/TrufflePrimitiveNodes.java
index 356a478..04c4796 100644
--- a/truffle/src/main/java/org/jruby/truffle/nodes/core/TrufflePrimitiveNodes.java
+++ b/truffle/src/main/java/org/jruby/truffle/nodes/core/TrufflePrimitiveNodes.java
@@ -127,6 +127,21 @@ public abstract class TrufflePrimitiveNodes {
 
     }
 
+    @CoreMethod(names = "clock_gettime_monotonic", onSingleton = true)
+    public abstract static class MonotonicTimeNode extends CoreMethodArrayArgumentsNode {
+
+        public MonotonicTimeNode(RubyContext context, SourceSection sourceSection) {
+            super(context, sourceSection);
+        }
+
+        @TruffleBoundary
+        @Specialization
+        public double clockGettimeMonotonic() {
+            return IterationsRunner.JNI_clock_gettime_monotonic();
+        }
+
+    }
+
     @CoreMethod(names = "gc_time", onSingleton = true)
     public abstract static class GCTimeNode extends CoreMethodArrayArgumentsNode {
 
```

but the class ``IterationsRunner`` is of course not found. How do I fix that part?

**Comment by cfbolz** [comment]
Ok, IterationsRunner is in an "unnamed package", which can't be used from any other Java code in a package. Do we make it a package?

**Comment by vext01** [comment]
Looks like we need to:
http://stackoverflow.com/questions/283816/how-to-access-java-classes-in-the-default-package

**Comment by cfbolz** [comment]
reflection, do we really want to do that?

**Comment by cfbolz** [comment]
Wouldn't that produce too much overhead for the timing call?

**Comment by vext01** [comment]
Woops. To be clear.

Looks like we do need to put out code in a package, due to `You can’t use classes in the default package from a named package`. I didn't mean to use reflection.
